// Code generated by protoc-gen-go. DO NOT EDIT.
// These are the message types and service definitions auto-generated from user_service.proto

package main

import (
	fmt "fmt"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	sync "sync"
)

// ========== MESSAGE TYPES (Binary Serializable) ==========

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age      int32  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	IsActive bool   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
}

func (x *User) String() string {
	return fmt.Sprintf("User{Id:%d, Name:%q, Email:%q, Age:%d, IsActive:%v}", x.Id, x.Name, x.Email, x.Age, x.IsActive)
}

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Age   int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
}

func (x *CreateUserRequest) String() string {
	return fmt.Sprintf("CreateUserRequest{Name:%q, Email:%q, Age:%d}", x.Name, x.Email, x.Age)
}

type CreateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User    *User  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
}

func (x *CreateUserResponse) String() string {
	return fmt.Sprintf("CreateUserResponse{Success:%v, Message:%q, User:%v}", x.Success, x.Message, x.User)
}

type GetUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
}

func (x *GetUserRequest) String() string {
	return fmt.Sprintf("GetUserRequest{Id:%d}", x.Id)
}

type ListUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
}

func (x *ListUsersRequest) String() string {
	return fmt.Sprintf("ListUsersRequest{Limit:%d, Offset:%d}", x.Limit, x.Offset)
}

type ListUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total int32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
}

func (x *ListUsersResponse) String() string {
	return fmt.Sprintf("ListUsersResponse{Total:%d, Users:%d items}", x.Total, len(x.Users))
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age   int32  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
}

func (x *UpdateUserRequest) String() string {
	return fmt.Sprintf("UpdateUserRequest{Id:%d, Name:%q, Email:%q, Age:%d}", x.Id, x.Name, x.Email, x.Age)
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User    *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
}

func (x *UpdateUserResponse) String() string {
	return fmt.Sprintf("UpdateUserResponse{Success:%v, User:%v}", x.Success, x.User)
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
}

func (x *DeleteUserRequest) String() string {
	return fmt.Sprintf("DeleteUserRequest{Id:%d}", x.Id)
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
}

func (x *DeleteUserResponse) String() string {
	return fmt.Sprintf("DeleteUserResponse{Success:%v, Message:%q}", x.Success, x.Message)
}

